import type { Rule } from "../types.js";

/** Payments, messaging, monitoring — the long tail of prefixed SaaS tokens. */
export const saasRules: Rule[] = [
  {
    id: "stripe-secret-key",
    provider: "stripe",
    description: "Stripe secret or restricted key",
    regex: /\b((?:sk|rk)_live_[A-Za-z0-9]{24,99})\b/g,
    prefilter: ["sk_live_", "rk_live_"],
    group: 1,
    entropyMin: 3.5,
    confidence: "high",
  },
  // No rule for sk_test_ / rk_test_ keys: they cannot move money, and the
  // placeholder suppressor drops anything with a `test` token anyway, so the
  // rule would never fire.
  {
    id: "slack-bot-token",
    provider: "slack",
    description: "Slack bot/user/app token",
    regex: /\b(xox[baprs]-[0-9A-Za-z-]{10,72})\b/g,
    prefilter: ["xoxb-", "xoxp-", "xoxa-", "xoxr-", "xoxs-"],
    group: 1,
    entropyMin: 3.0,
    confidence: "high",
  },
  {
    id: "slack-app-token",
    provider: "slack",
    description: "Slack app-level token",
    regex: /\b(xapp-\d-[A-Z0-9]+-\d+-[a-f0-9]{64})\b/g,
    prefilter: ["xapp-"],
    group: 1,
    confidence: "high",
  },
  {
    id: "slack-webhook-url",
    provider: "slack",
    description: "Slack incoming webhook URL",
    regex: /(https:\/\/hooks\.slack\.com\/services\/T[A-Za-z0-9_]+\/B[A-Za-z0-9_]+\/[A-Za-z0-9_]{20,})/g,
    prefilter: ["hooks.slack.com"],
    group: 1,
    confidence: "high",
  },
  {
    id: "discord-bot-token",
    provider: "discord",
    description: "Discord bot token",
    regex: /\b([MNO][A-Za-z0-9_-]{23}\.[A-Za-z0-9_-]{6}\.[A-Za-z0-9_-]{27})\b/g,
    group: 1,
    entropyMin: 4.0,
    confidence: "medium",
  },
  {
    id: "telegram-bot-token",
    provider: "telegram",
    description: "Telegram bot token",
    regex: /\b(\d{8,10}:AA[A-Za-z0-9_-]{32,34})\b/g,
    prefilter: [":AA"],
    group: 1,
    confidence: "high",
  },
  {
    id: "twilio-api-key",
    provider: "twilio",
    description: "Twilio account SID / API key",
    regex: /\b((?:AC|SK)[a-f0-9]{32})\b/g,
    prefilter: ["AC", "SK"],
    group: 1,
    entropyMin: 3.2,
    confidence: "medium",
  },
  {
    id: "sendgrid-api-key",
    provider: "sendgrid",
    description: "SendGrid API key",
    regex: /\b(SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43})\b/g,
    prefilter: ["SG."],
    group: 1,
    confidence: "high",
  },
  {
    id: "mailgun-api-key",
    provider: "mailgun",
    description: "Mailgun API key",
    regex: /\b(key-[a-f0-9]{32})\b/g,
    prefilter: ["key-"],
    group: 1,
    entropyMin: 3.2,
    confidence: "high",
  },
  {
    id: "shopify-access-token",
    provider: "shopify",
    description: "Shopify access token",
    regex: /\b(shp(?:at|ca|pa|ss)_[a-fA-F0-9]{32})\b/g,
    prefilter: ["shpat_", "shpca_", "shppa_", "shpss_"],
    group: 1,
    confidence: "high",
  },
  {
    id: "square-access-token",
    provider: "square",
    description: "Square access token",
    regex: /\b(sq0(?:atp|csp|idp)-[A-Za-z0-9_-]{22,43})\b/g,
    prefilter: ["sq0atp-", "sq0csp-", "sq0idp-"],
    group: 1,
    confidence: "high",
  },
  {
    id: "datadog-api-key",
    provider: "datadog",
    description: "Datadog API key",
    regex: /(?:datadog|dd)[_.\-]?api[_.\-]?key["'\s]*[:=]\s*["']?([a-f0-9]{32})["']?/gi,
    prefilter: ["datadog", "DATADOG", "dd_api", "DD_API"],
    group: 1,
    entropyMin: 3.2,
    confidence: "high",
  },
  {
    id: "new-relic-license-key",
    provider: "newrelic",
    description: "New Relic license key",
    regex: /\b(NRAK-[A-Z0-9]{27})\b/g,
    prefilter: ["NRAK-"],
    group: 1,
    confidence: "high",
  },
  {
    id: "supabase-service-role-key",
    provider: "supabase",
    description: "Supabase service role key",
    regex: /\b(sbp_[a-f0-9]{40})\b/g,
    prefilter: ["sbp_"],
    group: 1,
    confidence: "high",
  },
  {
    id: "vercel-token",
    provider: "vercel",
    description: "Vercel API token",
    regex: /vercel[_.\-]?token["'\s]*[:=]\s*["']?([A-Za-z0-9]{24})["']?/gi,
    prefilter: ["vercel", "VERCEL", "Vercel"],
    group: 1,
    entropyMin: 3.5,
    confidence: "medium",
  },
];
