import type { Rule } from "../types.js";

/** GitHub, GitLab, Bitbucket, npm, PyPI — the package and source hosts. */
export const vcsRules: Rule[] = [
  {
    id: "github-pat-classic",
    provider: "github",
    description: "GitHub personal access token (classic)",
    // ghp personal, gho OAuth, ghu user-to-server, ghs server-to-server,
    // ghr refresh. Same 36-char body on all of them.
    regex: /\b(gh[pousr]_[A-Za-z0-9]{36})\b/g,
    prefilter: ["ghp_", "gho_", "ghu_", "ghs_", "ghr_"],
    group: 1,
    entropyMin: 3.2,
    confidence: "high",
  },
  {
    id: "github-pat-fine-grained",
    provider: "github",
    description: "GitHub fine-grained personal access token",
    regex: /\b(github_pat_[A-Za-z0-9_]{60,90})\b/g,
    prefilter: ["github_pat_"],
    group: 1,
    entropyMin: 3.5,
    confidence: "high",
  },
  {
    id: "github-app-jwt-key",
    provider: "github",
    description: "GitHub App installation token",
    regex: /\b(ghs_[A-Za-z0-9]{36})\b/g,
    prefilter: ["ghs_"],
    group: 1,
    confidence: "high",
  },
  {
    id: "gitlab-pat",
    provider: "gitlab",
    description: "GitLab personal access token",
    regex: /\b(glpat-[A-Za-z0-9_-]{20,})\b/g,
    prefilter: ["glpat-"],
    group: 1,
    entropyMin: 3.2,
    confidence: "high",
  },
  {
    id: "gitlab-runner-token",
    provider: "gitlab",
    description: "GitLab runner registration token",
    regex: /\b(GR1348941[A-Za-z0-9_-]{20})\b/g,
    prefilter: ["GR1348941"],
    group: 1,
    confidence: "high",
  },
  {
    id: "npm-access-token",
    provider: "npm",
    description: "npm access token",
    regex: /\b(npm_[A-Za-z0-9]{36})\b/g,
    prefilter: ["npm_"],
    group: 1,
    entropyMin: 3.2,
    confidence: "high",
  },
  {
    id: "pypi-upload-token",
    provider: "pypi",
    description: "PyPI upload token",
    regex: /\b(pypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,})\b/g,
    prefilter: ["pypi-AgEIcHlwaS5vcmc"],
    group: 1,
    confidence: "high",
  },
  {
    id: "bitbucket-client-secret",
    provider: "bitbucket",
    description: "Bitbucket client secret",
    regex: /bitbucket[_.\-]?client[_.\-]?secret["'\s]*[:=]\s*["']?([A-Za-z0-9_-]{64})["']?/gi,
    prefilter: ["bitbucket", "BITBUCKET", "Bitbucket"],
    group: 1,
    entropyMin: 3.8,
    confidence: "high",
  },
];
